// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace ASPMVC.CodedUITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// InitIndexPage
        /// </summary>
        public void InitIndexPage()
        {
            #region Variable Declarations
            HtmlHyperlink uIWięcejinformacjiHyperlink = this.UITawitrynaniejestbezpWindow.UITawitrynaniejestbezpDocument.UIWięcejinformacjiPane.UIWięcejinformacjiHyperlink;
            HtmlHyperlink uIPrzejdźdotejstronysiHyperlink = this.UITawitrynaniejestbezpWindow.UITawitrynaniejestbezpDocument.UIPrzejdźdotejstronysiHyperlink;
            #endregion

            // Click 'Więcej informacji' link
            Mouse.Click(uIWięcejinformacjiHyperlink, new Point(40, 11));

            // Click 'Przejdź do tej strony sieci web (niezalecane)' link
            Mouse.Click(uIPrzejdźdotejstronysiHyperlink, new Point(265, 10));
        }
        
        /// <summary>
        /// LogInAsAdmin - Use 'LogInAsAdminParams' to pass parameters into this method.
        /// </summary>
        public void LogInAsAdmin()
        {
            #region Variable Declarations
            HtmlHyperlink uILoginHyperlink = this.UIHomePageGunServiceInWindow.UIHomePageGunServiceDocument.UILoginHyperlink;
            HtmlEdit uIEmailEdit = this.UILoginGunServiceInterWindow.UILoginGunServiceDocument.UIEmailEdit;
            HtmlEdit uIPasswordEdit = this.UILoginGunServiceInterWindow.UILoginGunServiceDocument.UIPasswordEdit;
            HtmlButton uILoginButton = this.UILoginGunServiceInterWindow.UILoginGunServiceDocument.UIAccountCustom.UILoginButton;
            #endregion

            // Click 'Login' link
            Mouse.Click(uILoginHyperlink, new Point(33, 24));

            // Type 'admin@asp.net' in 'Email' text box
            uIEmailEdit.Text = this.LogInAsAdminParams.UIEmailEditText;

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.LogInAsAdminParams.UIPasswordEditPassword;

            // Click 'Log in' button
            Mouse.Click(uILoginButton, new Point(42, 17));
        }
        
        /// <summary>
        /// GoToGunsSection
        /// </summary>
        public void GoToGunsSection()
        {
            #region Variable Declarations
            HtmlHyperlink uIGunsHyperlink = this.UIHomePageGunServiceInWindow.UIHomePageGunServiceDocument.UIGunsHyperlink;
            #endregion

            // Click 'Guns' link
            Mouse.Click(uIGunsHyperlink, new Point(56, 20));
        }
        
        /// <summary>
        /// GoToCreateNew
        /// </summary>
        public void GoToCreateNew()
        {
            #region Variable Declarations
            HtmlHyperlink uICreateNewHyperlink = this.UIGunsGunServiceInternWindow.UIGunsGunServiceDocument.UICreateNewHyperlink;
            #endregion

            // Click 'Create New' link
            Mouse.Click(uICreateNewHyperlink, new Point(33, 18));
        }
        
        /// <summary>
        /// AssertMethodAdminLoggedIn - Use 'AssertMethodAdminLoggedInExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethodAdminLoggedIn()
        {
            #region Variable Declarations
            HtmlHyperlink uICreateNewHyperlink = this.UIGunsGunServiceInternWindow.UIGunsGunServiceDocument.UICreateNewHyperlink;
            #endregion

            // Verify that the 'InnerText' property of 'Create New' link equals 'Create New'
            Assert.AreEqual(this.AssertMethodAdminLoggedInExpectedValues.UICreateNewHyperlinkInnerText, uICreateNewHyperlink.InnerText, "Page load error");
        }
        
        /// <summary>
        /// CreateNewGun - Use 'CreateNewGunParams' to pass parameters into this method.
        /// </summary>
        public void CreateNewGun()
        {
            #region Variable Declarations
            HtmlEdit uINameEdit = this.UICreateGunServiceInteWindow.UICreateGunServiceDocument.UINameEdit;
            HtmlEdit uIReleaseDateEdit = this.UICreateGunServiceInteWindow.UICreateGunServiceDocument.UIReleaseDateEdit;
            HtmlComboBox uITypeComboBox = this.UICreateGunServiceInteWindow.UICreateGunServiceDocument.UITypeComboBox;
            HtmlEdit uICaliberEdit = this.UICreateGunServiceInteWindow.UICreateGunServiceDocument.UICaliberEdit;
            HtmlEdit uIPriceEdit = this.UICreateGunServiceInteWindow.UICreateGunServiceDocument.UIPriceEdit;
            HtmlComboBox uIManufacturerIDComboBox = this.UICreateGunServiceInteWindow.UICreateGunServiceDocument.UIManufacturerIDComboBox;
            HtmlInputButton uICreateButton = this.UICreateGunServiceInteWindow.UICreateGunServiceDocument.UICreateButton;
            #endregion

            // Type 'USP' in 'Name' text box
            uINameEdit.Text = this.CreateNewGunParams.UINameEditText;

            // Type '1987-05-11' in 'Release Date' text box
            uIReleaseDateEdit.Text = this.CreateNewGunParams.UIReleaseDateEditText;

            // Select 'Pistol' in 'Type' combo box
            uITypeComboBox.SelectedItem = this.CreateNewGunParams.UITypeComboBoxSelectedItem;

            // Type '9mm' in 'Caliber' text box
            uICaliberEdit.Text = this.CreateNewGunParams.UICaliberEditText;

            // Type '899' in 'Price' text box
            uIPriceEdit.Text = this.CreateNewGunParams.UIPriceEditText;

            // Select 'H&K' in 'ManufacturerID' combo box
            uIManufacturerIDComboBox.SelectedItem = this.CreateNewGunParams.UIManufacturerIDComboBoxSelectedItem;

            // Click 'Create' button
            Mouse.Click(uICreateButton, new Point(49, 19));
        }
        
        /// <summary>
        /// CheckAddedGunDetails
        /// </summary>
        public void CheckAddedGunDetails()
        {
            #region Variable Declarations
            HtmlHyperlink uIDetailsHyperlink = this.UIGunsGunServiceInternWindow.UIGunsGunServiceDocument.UIDetailsHyperlink;
            #endregion

            // Click 'Details' link
            Mouse.Click(uIDetailsHyperlink, new Point(42, 12));
        }
        
        /// <summary>
        /// GoBackToGuns
        /// </summary>
        public void GoBackToGuns()
        {
            #region Variable Declarations
            HtmlHyperlink uIBacktoListHyperlink = this.UIDetailsGunServiceIntWindow.UIDetailsGunServiceDocument.UIBacktoListHyperlink;
            #endregion

            // Click 'Back to List' link
            Mouse.Click(uIBacktoListHyperlink, new Point(60, 13));
        }
        
        /// <summary>
        /// EditAddedGun - Use 'EditAddedGunParams' to pass parameters into this method.
        /// </summary>
        public void EditAddedGun()
        {
            #region Variable Declarations
            HtmlHyperlink uIEditHyperlink = this.UIGunsGunServiceInternWindow.UIGunsGunServiceDocument.UIEditHyperlink;
            HtmlComboBox uITypeComboBox = this.UIGunsGunServiceInternWindow.UIEditGunServiceDocument.UITypeComboBox;
            HtmlEdit uIPriceEdit = this.UIGunsGunServiceInternWindow.UIEditGunServiceDocument.UIPriceEdit;
            HtmlInputButton uISaveButton = this.UIGunsGunServiceInternWindow.UIEditGunServiceDocument.UISaveButton;
            #endregion

            // Click 'Edit' link
            Mouse.Click(uIEditHyperlink, new Point(10, 14));

            // Select 'Sniper' in 'Type' combo box
            uITypeComboBox.SelectedItem = this.EditAddedGunParams.UITypeComboBoxSelectedItem;

            // Type '675.35' in 'Price' text box
            uIPriceEdit.Text = this.EditAddedGunParams.UIPriceEditText;

            // Click 'Save' button
            Mouse.Click(uISaveButton, new Point(25, 22));
        }
        
        /// <summary>
        /// DeleteAddedGun
        /// </summary>
        public void DeleteAddedGun()
        {
            #region Variable Declarations
            HtmlHyperlink uIDeleteHyperlink = this.UIGunsGunServiceInternWindow.UIGunsGunServiceDocument.UIDeleteHyperlink;
            HtmlInputButton uIDeleteButton = this.UIGunsGunServiceInternWindow.UIDeleteGunServiceDocument.UIDeleteButton;
            #endregion

            // Click 'Delete' link
            Mouse.Click(uIDeleteHyperlink, new Point(15, 12));

            // Click 'Delete' button
            Mouse.Click(uIDeleteButton, new Point(32, 17));
        }
        
        /// <summary>
        /// GoBackToIndexAndLogout
        /// </summary>
        public void GoBackToIndexAndLogout()
        {
            #region Variable Declarations
            HtmlHyperlink uIHomeHyperlink = this.UIGunsGunServiceInternWindow.UIGunsGunServiceDocument.UIHomeHyperlink;
            HtmlButton uILogoutButton = this.UIHomePageGunServiceInWindow.UIHomePageGunServiceDocument.UILogoutButton;
            #endregion

            // Click 'Home' link
            Mouse.Click(uIHomeHyperlink, new Point(40, 23));

            // Click 'Logout' button
            Mouse.Click(uILogoutButton, new Point(36, 18));
        }
        
        #region Properties
        public virtual LogInAsAdminParams LogInAsAdminParams
        {
            get
            {
                if ((this.mLogInAsAdminParams == null))
                {
                    this.mLogInAsAdminParams = new LogInAsAdminParams();
                }
                return this.mLogInAsAdminParams;
            }
        }
        
        public virtual AssertMethodAdminLoggedInExpectedValues AssertMethodAdminLoggedInExpectedValues
        {
            get
            {
                if ((this.mAssertMethodAdminLoggedInExpectedValues == null))
                {
                    this.mAssertMethodAdminLoggedInExpectedValues = new AssertMethodAdminLoggedInExpectedValues();
                }
                return this.mAssertMethodAdminLoggedInExpectedValues;
            }
        }
        
        public virtual CreateNewGunParams CreateNewGunParams
        {
            get
            {
                if ((this.mCreateNewGunParams == null))
                {
                    this.mCreateNewGunParams = new CreateNewGunParams();
                }
                return this.mCreateNewGunParams;
            }
        }
        
        public virtual EditAddedGunParams EditAddedGunParams
        {
            get
            {
                if ((this.mEditAddedGunParams == null))
                {
                    this.mEditAddedGunParams = new EditAddedGunParams();
                }
                return this.mEditAddedGunParams;
            }
        }
        
        public UITawitrynaniejestbezpWindow UITawitrynaniejestbezpWindow
        {
            get
            {
                if ((this.mUITawitrynaniejestbezpWindow == null))
                {
                    this.mUITawitrynaniejestbezpWindow = new UITawitrynaniejestbezpWindow();
                }
                return this.mUITawitrynaniejestbezpWindow;
            }
        }
        
        public UIHomePageGunServiceInWindow UIHomePageGunServiceInWindow
        {
            get
            {
                if ((this.mUIHomePageGunServiceInWindow == null))
                {
                    this.mUIHomePageGunServiceInWindow = new UIHomePageGunServiceInWindow();
                }
                return this.mUIHomePageGunServiceInWindow;
            }
        }
        
        public UILoginGunServiceInterWindow UILoginGunServiceInterWindow
        {
            get
            {
                if ((this.mUILoginGunServiceInterWindow == null))
                {
                    this.mUILoginGunServiceInterWindow = new UILoginGunServiceInterWindow();
                }
                return this.mUILoginGunServiceInterWindow;
            }
        }
        
        public UIGunsGunServiceInternWindow UIGunsGunServiceInternWindow
        {
            get
            {
                if ((this.mUIGunsGunServiceInternWindow == null))
                {
                    this.mUIGunsGunServiceInternWindow = new UIGunsGunServiceInternWindow();
                }
                return this.mUIGunsGunServiceInternWindow;
            }
        }
        
        public UICreateGunServiceInteWindow UICreateGunServiceInteWindow
        {
            get
            {
                if ((this.mUICreateGunServiceInteWindow == null))
                {
                    this.mUICreateGunServiceInteWindow = new UICreateGunServiceInteWindow();
                }
                return this.mUICreateGunServiceInteWindow;
            }
        }
        
        public UIDetailsGunServiceIntWindow UIDetailsGunServiceIntWindow
        {
            get
            {
                if ((this.mUIDetailsGunServiceIntWindow == null))
                {
                    this.mUIDetailsGunServiceIntWindow = new UIDetailsGunServiceIntWindow();
                }
                return this.mUIDetailsGunServiceIntWindow;
            }
        }
        #endregion
        
        #region Fields
        private LogInAsAdminParams mLogInAsAdminParams;
        
        private AssertMethodAdminLoggedInExpectedValues mAssertMethodAdminLoggedInExpectedValues;
        
        private CreateNewGunParams mCreateNewGunParams;
        
        private EditAddedGunParams mEditAddedGunParams;
        
        private UITawitrynaniejestbezpWindow mUITawitrynaniejestbezpWindow;
        
        private UIHomePageGunServiceInWindow mUIHomePageGunServiceInWindow;
        
        private UILoginGunServiceInterWindow mUILoginGunServiceInterWindow;
        
        private UIGunsGunServiceInternWindow mUIGunsGunServiceInternWindow;
        
        private UICreateGunServiceInteWindow mUICreateGunServiceInteWindow;
        
        private UIDetailsGunServiceIntWindow mUIDetailsGunServiceIntWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LogInAsAdmin'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class LogInAsAdminParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'admin@asp.net' in 'Email' text box
        /// </summary>
        public string UIEmailEditText = "admin@asp.net";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "AFVcWLObwIYaS3KEjwZPrKJioOUfBfH+";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethodAdminLoggedIn'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class AssertMethodAdminLoggedInExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Create New' link equals 'Create New'
        /// </summary>
        public string UICreateNewHyperlinkInnerText = "Create New";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'CreateNewGun'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class CreateNewGunParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'USP' in 'Name' text box
        /// </summary>
        public string UINameEditText = "USP";
        
        /// <summary>
        /// Type '1987-05-11' in 'Release Date' text box
        /// </summary>
        public string UIReleaseDateEditText = "1987-05-11";
        
        /// <summary>
        /// Select 'Pistol' in 'Type' combo box
        /// </summary>
        public string UITypeComboBoxSelectedItem = "Pistol";
        
        /// <summary>
        /// Type '9mm' in 'Caliber' text box
        /// </summary>
        public string UICaliberEditText = "9mm";
        
        /// <summary>
        /// Type '899' in 'Price' text box
        /// </summary>
        public string UIPriceEditText = "899";
        
        /// <summary>
        /// Select 'H&K' in 'ManufacturerID' combo box
        /// </summary>
        public string UIManufacturerIDComboBoxSelectedItem = "H&K";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EditAddedGun'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class EditAddedGunParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Sniper' in 'Type' combo box
        /// </summary>
        public string UITypeComboBoxSelectedItem = "Sniper";
        
        /// <summary>
        /// Type '675.35' in 'Price' text box
        /// </summary>
        public string UIPriceEditText = "675.35";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITawitrynaniejestbezpWindow : BrowserWindow
    {
        
        public UITawitrynaniejestbezpWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Ta witryna nie jest bezpieczna";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Ta witryna nie jest bezpieczna");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UITawitrynaniejestbezpDocument UITawitrynaniejestbezpDocument
        {
            get
            {
                if ((this.mUITawitrynaniejestbezpDocument == null))
                {
                    this.mUITawitrynaniejestbezpDocument = new UITawitrynaniejestbezpDocument(this);
                }
                return this.mUITawitrynaniejestbezpDocument;
            }
        }
        #endregion
        
        #region Fields
        private UITawitrynaniejestbezpDocument mUITawitrynaniejestbezpDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITawitrynaniejestbezpDocument : HtmlDocument
    {
        
        public UITawitrynaniejestbezpDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Ta witryna nie jest bezpieczna";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/invalidcert.htm";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "res://ieframe.dll/invalidcert.htm?SSLError=16777216#https://localhost:5001/";
            this.WindowTitles.Add("Ta witryna nie jest bezpieczna");
            #endregion
        }
        
        #region Properties
        public UIWięcejinformacjiPane UIWięcejinformacjiPane
        {
            get
            {
                if ((this.mUIWięcejinformacjiPane == null))
                {
                    this.mUIWięcejinformacjiPane = new UIWięcejinformacjiPane(this);
                }
                return this.mUIWięcejinformacjiPane;
            }
        }
        
        public HtmlHyperlink UIPrzejdźdotejstronysiHyperlink
        {
            get
            {
                if ((this.mUIPrzejdźdotejstronysiHyperlink == null))
                {
                    this.mUIPrzejdźdotejstronysiHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIPrzejdźdotejstronysiHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "overridelink";
                    this.mUIPrzejdźdotejstronysiHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIPrzejdźdotejstronysiHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIPrzejdźdotejstronysiHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Przejdź do tej strony sieci web (niezalecane)";
                    this.mUIPrzejdźdotejstronysiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIPrzejdźdotejstronysiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIPrzejdźdotejstronysiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://localhost:5001/";
                    this.mUIPrzejdźdotejstronysiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIPrzejdźdotejstronysiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=\"overridelink\" href=\"https://localhos";
                    this.mUIPrzejdźdotejstronysiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUIPrzejdźdotejstronysiHyperlink.WindowTitles.Add("Ta witryna nie jest bezpieczna");
                    #endregion
                }
                return this.mUIPrzejdźdotejstronysiHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private UIWięcejinformacjiPane mUIWięcejinformacjiPane;
        
        private HtmlHyperlink mUIPrzejdźdotejstronysiHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIWięcejinformacjiPane : HtmlSpan
    {
        
        public UIWięcejinformacjiPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "moreInfoContainer";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Więcej informacji";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"moreInfoContainer\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Ta witryna nie jest bezpieczna");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIWięcejinformacjiHyperlink
        {
            get
            {
                if ((this.mUIWięcejinformacjiHyperlink == null))
                {
                    this.mUIWięcejinformacjiHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIWięcejinformacjiHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIWięcejinformacjiHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIWięcejinformacjiHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIWięcejinformacjiHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Więcej informacji";
                    this.mUIWięcejinformacjiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "expandCollapse(\'infoBlockID\',%20true);";
                    this.mUIWięcejinformacjiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIWięcejinformacjiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "javascript:expandCollapse(\'infoBlockID\', true);";
                    this.mUIWięcejinformacjiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIWięcejinformacjiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"javascript:expandCollapse(\'infoBlo";
                    this.mUIWięcejinformacjiHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIWięcejinformacjiHyperlink.WindowTitles.Add("Ta witryna nie jest bezpieczna");
                    #endregion
                }
                return this.mUIWięcejinformacjiHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIWięcejinformacjiHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHomePageGunServiceInWindow : BrowserWindow
    {
        
        public UIHomePageGunServiceInWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Home Page - Gun Service";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Home Page - Gun Service");
            this.WindowTitles.Add("Guns - Gun Service");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomePageGunServiceDocument UIHomePageGunServiceDocument
        {
            get
            {
                if ((this.mUIHomePageGunServiceDocument == null))
                {
                    this.mUIHomePageGunServiceDocument = new UIHomePageGunServiceDocument(this);
                }
                return this.mUIHomePageGunServiceDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePageGunServiceDocument mUIHomePageGunServiceDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHomePageGunServiceDocument : HtmlDocument
    {
        
        public UIHomePageGunServiceDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page - Gun Service";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://localhost:5001/";
            this.WindowTitles.Add("Home Page - Gun Service");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UILoginHyperlink
        {
            get
            {
                if ((this.mUILoginHyperlink == null))
                {
                    this.mUILoginHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUILoginHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Identity/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://localhost:5001/Identity/Account/Login";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "nav-link text-light";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"nav-link text-light\" href=\"/Ident";
                    this.mUILoginHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUILoginHyperlink.WindowTitles.Add("Home Page - Gun Service");
                    #endregion
                }
                return this.mUILoginHyperlink;
            }
        }
        
        public HtmlHyperlink UIGunsHyperlink
        {
            get
            {
                if ((this.mUIGunsHyperlink == null))
                {
                    this.mUIGunsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIGunsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIGunsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIGunsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIGunsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Guns";
                    this.mUIGunsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Guns";
                    this.mUIGunsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIGunsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://localhost:5001/Guns";
                    this.mUIGunsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIGunsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Guns\"";
                    this.mUIGunsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUIGunsHyperlink.WindowTitles.Add("Home Page - Gun Service");
                    #endregion
                }
                return this.mUIGunsHyperlink;
            }
        }
        
        public HtmlButton UILogoutButton
        {
            get
            {
                if ((this.mUILogoutButton == null))
                {
                    this.mUILogoutButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUILogoutButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUILogoutButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUILogoutButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Logout";
                    this.mUILogoutButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUILogoutButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUILogoutButton.FilterProperties[HtmlButton.PropertyNames.Class] = "nav-link btn btn-link text-light";
                    this.mUILogoutButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"nav-link btn btn-link text-light\"";
                    this.mUILogoutButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUILogoutButton.WindowTitles.Add("Home Page - Gun Service");
                    #endregion
                }
                return this.mUILogoutButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUILoginHyperlink;
        
        private HtmlHyperlink mUIGunsHyperlink;
        
        private HtmlButton mUILogoutButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UILoginGunServiceInterWindow : BrowserWindow
    {
        
        public UILoginGunServiceInterWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Log in - Gun Service";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Log in - Gun Service");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UILoginGunServiceDocument UILoginGunServiceDocument
        {
            get
            {
                if ((this.mUILoginGunServiceDocument == null))
                {
                    this.mUILoginGunServiceDocument = new UILoginGunServiceDocument(this);
                }
                return this.mUILoginGunServiceDocument;
            }
        }
        #endregion
        
        #region Fields
        private UILoginGunServiceDocument mUILoginGunServiceDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UILoginGunServiceDocument : HtmlDocument
    {
        
        public UILoginGunServiceDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Log in - Gun Service";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Identity/Account/Login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://localhost:5001/Identity/Account/Login";
            this.WindowTitles.Add("Log in - Gun Service");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIEmailEdit
        {
            get
            {
                if ((this.mUIEmailEdit == null))
                {
                    this.mUIEmailEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Input_Email";
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Input.Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Input.Email\" class=\"form-control\" ";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIEmailEdit.WindowTitles.Add("Log in - Gun Service");
                    #endregion
                }
                return this.mUIEmailEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Input_Password";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Input.Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Input.Password\" class=\"form-contro";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIPasswordEdit.WindowTitles.Add("Log in - Gun Service");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public UIAccountCustom UIAccountCustom
        {
            get
            {
                if ((this.mUIAccountCustom == null))
                {
                    this.mUIAccountCustom = new UIAccountCustom(this);
                }
                return this.mUIAccountCustom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIEmailEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private UIAccountCustom mUIAccountCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAccountCustom : HtmlCustom
    {
        
        public UIAccountCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "FORM";
            this.SearchProperties["Id"] = "account";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"account\" method=\"post\" novalidate=\"n";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Log in - Gun Service");
            #endregion
        }
        
        #region Properties
        public HtmlButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Log in";
                    this.mUILoginButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-primary\" type=\"submit\"";
                    this.mUILoginButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUILoginButton.WindowTitles.Add("Log in - Gun Service");
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUILoginButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIGunsGunServiceInternWindow : BrowserWindow
    {
        
        public UIGunsGunServiceInternWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Guns - Gun Service";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Guns - Gun Service");
            this.WindowTitles.Add("Edit - Gun Service");
            this.WindowTitles.Add("Delete - Gun Service");
            this.WindowTitles.Add("Home Page - Gun Service");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIGunsGunServiceDocument UIGunsGunServiceDocument
        {
            get
            {
                if ((this.mUIGunsGunServiceDocument == null))
                {
                    this.mUIGunsGunServiceDocument = new UIGunsGunServiceDocument(this);
                }
                return this.mUIGunsGunServiceDocument;
            }
        }
        
        public UIEditGunServiceDocument UIEditGunServiceDocument
        {
            get
            {
                if ((this.mUIEditGunServiceDocument == null))
                {
                    this.mUIEditGunServiceDocument = new UIEditGunServiceDocument(this);
                }
                return this.mUIEditGunServiceDocument;
            }
        }
        
        public UIDeleteGunServiceDocument UIDeleteGunServiceDocument
        {
            get
            {
                if ((this.mUIDeleteGunServiceDocument == null))
                {
                    this.mUIDeleteGunServiceDocument = new UIDeleteGunServiceDocument(this);
                }
                return this.mUIDeleteGunServiceDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIGunsGunServiceDocument mUIGunsGunServiceDocument;
        
        private UIEditGunServiceDocument mUIEditGunServiceDocument;
        
        private UIDeleteGunServiceDocument mUIDeleteGunServiceDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIGunsGunServiceDocument : HtmlDocument
    {
        
        public UIGunsGunServiceDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Guns - Gun Service";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Guns";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://localhost:5001/Guns";
            this.WindowTitles.Add("Guns - Gun Service");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UICreateNewHyperlink
        {
            get
            {
                if ((this.mUICreateNewHyperlink == null))
                {
                    this.mUICreateNewHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Create New";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Guns/Create";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://localhost:5001/Guns/Create";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Guns/Create\"";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "7";
                    this.mUICreateNewHyperlink.WindowTitles.Add("Guns - Gun Service");
                    #endregion
                }
                return this.mUICreateNewHyperlink;
            }
        }
        
        public HtmlHyperlink UIDetailsHyperlink
        {
            get
            {
                if ((this.mUIDetailsHyperlink == null))
                {
                    this.mUIDetailsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIDetailsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIDetailsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIDetailsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIDetailsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Details";
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Guns/Details/5";
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://localhost:5001/Guns/Details/5";
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Guns/Details/5\"";
                    this.mUIDetailsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "22";
                    this.mUIDetailsHyperlink.WindowTitles.Add("Guns - Gun Service");
                    #endregion
                }
                return this.mUIDetailsHyperlink;
            }
        }
        
        public HtmlHyperlink UIEditHyperlink
        {
            get
            {
                if ((this.mUIEditHyperlink == null))
                {
                    this.mUIEditHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIEditHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIEditHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIEditHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIEditHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Edit";
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Guns/Edit/5";
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://localhost:5001/Guns/Edit/5";
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Guns/Edit/5\"";
                    this.mUIEditHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "20";
                    this.mUIEditHyperlink.WindowTitles.Add("Guns - Gun Service");
                    #endregion
                }
                return this.mUIEditHyperlink;
            }
        }
        
        public HtmlHyperlink UIDeleteHyperlink
        {
            get
            {
                if ((this.mUIDeleteHyperlink == null))
                {
                    this.mUIDeleteHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIDeleteHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIDeleteHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIDeleteHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIDeleteHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Delete";
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Guns/Delete/5";
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://localhost:5001/Guns/Delete/5";
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Guns/Delete/5\"";
                    this.mUIDeleteHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "21";
                    this.mUIDeleteHyperlink.WindowTitles.Add("Guns - Gun Service");
                    #endregion
                }
                return this.mUIDeleteHyperlink;
            }
        }
        
        public HtmlHyperlink UIHomeHyperlink
        {
            get
            {
                if ((this.mUIHomeHyperlink == null))
                {
                    this.mUIHomeHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Home";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://localhost:5001/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/\"";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIHomeHyperlink.WindowTitles.Add("Guns - Gun Service");
                    #endregion
                }
                return this.mUIHomeHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUICreateNewHyperlink;
        
        private HtmlHyperlink mUIDetailsHyperlink;
        
        private HtmlHyperlink mUIEditHyperlink;
        
        private HtmlHyperlink mUIDeleteHyperlink;
        
        private HtmlHyperlink mUIHomeHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIEditGunServiceDocument : HtmlDocument
    {
        
        public UIEditGunServiceDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Edit - Gun Service";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Guns/Edit/5";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://localhost:5001/Guns/Edit/5";
            this.WindowTitles.Add("Edit - Gun Service");
            #endregion
        }
        
        #region Properties
        public HtmlComboBox UITypeComboBox
        {
            get
            {
                if ((this.mUITypeComboBox == null))
                {
                    this.mUITypeComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUITypeComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "Type";
                    this.mUITypeComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "Type";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = "Type";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "7";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "form-control";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"Type\" class=\"form-control\" id=\"Typ";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUITypeComboBox.WindowTitles.Add("Edit - Gun Service");
                    #endregion
                }
                return this.mUITypeComboBox;
            }
        }
        
        public HtmlEdit UIPriceEdit
        {
            get
            {
                if ((this.mUIPriceEdit == null))
                {
                    this.mUIPriceEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPriceEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Price";
                    this.mUIPriceEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Price";
                    this.mUIPriceEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Price";
                    this.mUIPriceEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIPriceEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPriceEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPriceEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Price\" class=\"form-control\" id=\"Pr";
                    this.mUIPriceEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "6";
                    this.mUIPriceEdit.WindowTitles.Add("Edit - Gun Service");
                    #endregion
                }
                return this.mUIPriceEdit;
            }
        }
        
        public HtmlInputButton UISaveButton
        {
            get
            {
                if ((this.mUISaveButton == null))
                {
                    this.mUISaveButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Save";
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-primary\" type=\"submit\" va";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "7";
                    this.mUISaveButton.WindowTitles.Add("Edit - Gun Service");
                    #endregion
                }
                return this.mUISaveButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlComboBox mUITypeComboBox;
        
        private HtmlEdit mUIPriceEdit;
        
        private HtmlInputButton mUISaveButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIDeleteGunServiceDocument : HtmlDocument
    {
        
        public UIDeleteGunServiceDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Delete - Gun Service";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Guns/Delete/5";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://localhost:5001/Guns/Delete/5";
            this.WindowTitles.Add("Delete - Gun Service");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UIDeleteButton
        {
            get
            {
                if ((this.mUIDeleteButton == null))
                {
                    this.mUIDeleteButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIDeleteButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIDeleteButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIDeleteButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Delete";
                    this.mUIDeleteButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIDeleteButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIDeleteButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-danger";
                    this.mUIDeleteButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-danger\" type=\"submit\" val";
                    this.mUIDeleteButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUIDeleteButton.WindowTitles.Add("Delete - Gun Service");
                    #endregion
                }
                return this.mUIDeleteButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUIDeleteButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UICreateGunServiceInteWindow : BrowserWindow
    {
        
        public UICreateGunServiceInteWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Create - Gun Service";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Create - Gun Service");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UICreateGunServiceDocument UICreateGunServiceDocument
        {
            get
            {
                if ((this.mUICreateGunServiceDocument == null))
                {
                    this.mUICreateGunServiceDocument = new UICreateGunServiceDocument(this);
                }
                return this.mUICreateGunServiceDocument;
            }
        }
        #endregion
        
        #region Fields
        private UICreateGunServiceDocument mUICreateGunServiceDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UICreateGunServiceDocument : HtmlDocument
    {
        
        public UICreateGunServiceDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Create - Gun Service";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Guns/Create";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://localhost:5001/Guns/Create";
            this.WindowTitles.Add("Create - Gun Service");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUINameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Name";
                    this.mUINameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Name";
                    this.mUINameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUINameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUINameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUINameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Name\" class=\"form-control\" id=\"Nam";
                    this.mUINameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUINameEdit.WindowTitles.Add("Create - Gun Service");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        
        public HtmlEdit UIReleaseDateEdit
        {
            get
            {
                if ((this.mUIReleaseDateEdit == null))
                {
                    this.mUIReleaseDateEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIReleaseDateEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ProductionDate";
                    this.mUIReleaseDateEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ProductionDate";
                    this.mUIReleaseDateEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Release Date";
                    this.mUIReleaseDateEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIReleaseDateEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIReleaseDateEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIReleaseDateEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"ProductionDate\" class=\"form-contro";
                    this.mUIReleaseDateEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIReleaseDateEdit.WindowTitles.Add("Create - Gun Service");
                    #endregion
                }
                return this.mUIReleaseDateEdit;
            }
        }
        
        public HtmlComboBox UITypeComboBox
        {
            get
            {
                if ((this.mUITypeComboBox == null))
                {
                    this.mUITypeComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUITypeComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "Type";
                    this.mUITypeComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "Type";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = "Type";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "6";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "form-control";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"Type\" class=\"form-control\" id=\"Typ";
                    this.mUITypeComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUITypeComboBox.WindowTitles.Add("Create - Gun Service");
                    #endregion
                }
                return this.mUITypeComboBox;
            }
        }
        
        public HtmlEdit UICaliberEdit
        {
            get
            {
                if ((this.mUICaliberEdit == null))
                {
                    this.mUICaliberEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICaliberEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Caliber";
                    this.mUICaliberEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Caliber";
                    this.mUICaliberEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Caliber";
                    this.mUICaliberEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICaliberEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICaliberEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUICaliberEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Caliber\" class=\"form-control\" id=\"";
                    this.mUICaliberEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUICaliberEdit.WindowTitles.Add("Create - Gun Service");
                    #endregion
                }
                return this.mUICaliberEdit;
            }
        }
        
        public HtmlEdit UIPriceEdit
        {
            get
            {
                if ((this.mUIPriceEdit == null))
                {
                    this.mUIPriceEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPriceEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Price";
                    this.mUIPriceEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Price";
                    this.mUIPriceEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Price";
                    this.mUIPriceEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIPriceEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPriceEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPriceEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Price\" class=\"form-control\" id=\"Pr";
                    this.mUIPriceEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "5";
                    this.mUIPriceEdit.WindowTitles.Add("Create - Gun Service");
                    #endregion
                }
                return this.mUIPriceEdit;
            }
        }
        
        public HtmlComboBox UIManufacturerIDComboBox
        {
            get
            {
                if ((this.mUIManufacturerIDComboBox == null))
                {
                    this.mUIManufacturerIDComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIManufacturerIDComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "ManufacturerID";
                    this.mUIManufacturerIDComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "ManufacturerID";
                    this.mUIManufacturerIDComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUIManufacturerIDComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIManufacturerIDComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIManufacturerIDComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "4";
                    this.mUIManufacturerIDComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "form-control";
                    this.mUIManufacturerIDComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "name=\"ManufacturerID\" class=\"form-contro";
                    this.mUIManufacturerIDComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "2";
                    this.mUIManufacturerIDComboBox.WindowTitles.Add("Create - Gun Service");
                    #endregion
                }
                return this.mUIManufacturerIDComboBox;
            }
        }
        
        public HtmlInputButton UICreateButton
        {
            get
            {
                if ((this.mUICreateButton == null))
                {
                    this.mUICreateButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Create";
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary";
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-primary\" type=\"submit\" va";
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "6";
                    this.mUICreateButton.WindowTitles.Add("Create - Gun Service");
                    #endregion
                }
                return this.mUICreateButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUINameEdit;
        
        private HtmlEdit mUIReleaseDateEdit;
        
        private HtmlComboBox mUITypeComboBox;
        
        private HtmlEdit mUICaliberEdit;
        
        private HtmlEdit mUIPriceEdit;
        
        private HtmlComboBox mUIManufacturerIDComboBox;
        
        private HtmlInputButton mUICreateButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIDetailsGunServiceIntWindow : BrowserWindow
    {
        
        public UIDetailsGunServiceIntWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Details - Gun Service";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Details - Gun Service");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIDetailsGunServiceDocument UIDetailsGunServiceDocument
        {
            get
            {
                if ((this.mUIDetailsGunServiceDocument == null))
                {
                    this.mUIDetailsGunServiceDocument = new UIDetailsGunServiceDocument(this);
                }
                return this.mUIDetailsGunServiceDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIDetailsGunServiceDocument mUIDetailsGunServiceDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIDetailsGunServiceDocument : HtmlDocument
    {
        
        public UIDetailsGunServiceDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Details - Gun Service";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Guns/Details/5";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://localhost:5001/Guns/Details/5";
            this.WindowTitles.Add("Details - Gun Service");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIBacktoListHyperlink
        {
            get
            {
                if ((this.mUIBacktoListHyperlink == null))
                {
                    this.mUIBacktoListHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIBacktoListHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIBacktoListHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIBacktoListHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIBacktoListHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Back to List";
                    this.mUIBacktoListHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Guns";
                    this.mUIBacktoListHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIBacktoListHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://localhost:5001/Guns";
                    this.mUIBacktoListHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIBacktoListHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Guns\"";
                    this.mUIBacktoListHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "10";
                    this.mUIBacktoListHyperlink.WindowTitles.Add("Details - Gun Service");
                    #endregion
                }
                return this.mUIBacktoListHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIBacktoListHyperlink;
        #endregion
    }
}
